### ISSUE TITLE
SPRING: pages required before 'go-live'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#40]
- [x] Setup MVS sites page. https://test-eu-pollinator.pantheonsite.io/list-sites
- [x] Add pan trap samples page. https://test-eu-pollinator.pantheonsite.io/add-pan-trap-samples
- [x] Create transect page. #35 
- [x] Add species data for pan traps page. https://test-eu-pollinator.pantheonsite.io/select-samples-species-data. #38
- [x] Add bycatch data for pan traps page.  https://test-eu-pollinator.pantheonsite.io/select-samples-bycatch-data
- [x] Add transect counts for sampling visit page. #36 
- [x] Update page text to remove developer notes
- [x] Tidy up user registration page. #39

**Comment by DavidRoy** [comment]
@andrewvanbreda confirm timetable for completing these tasks.  Aim for end of April at latest

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
The give you idea of timetable, my thought is it is feasible before end of April but could be tight depending on how things go. As a base set of work it should be ok, it really depends if we hit any hitches.
Also will Biren need time to setup live URL?

My thoughts on specific areas mentioned above are
- MVS Sites page - DONE
- Pan Traps page - Think just needs a country filter on square autocomplete. Last time I worked on this it was doing funny things, but hopefully can get working.
- Transact site editing page -> Not done should be straightforward
- Link pan trap page to Hoverflies/Bees - DONE
- Bycatch for pan traps. This is live on UKPoMS, not sure if further work required, but should be easy port as I did the code so know it well
- Transact data entry page, in process of port from EBMS, hard to comment as I don't know the code well. Hopefully it will work ok without much alteration. Medium amount of Warehouse setup required.
- Developer notes->easy to remove
- Tidy up registration -> should be easy enough, although sometimes can be an area that is fiddly to control.

**Comment by BirenRathod** [comment]
@andrewvanbreda I'm fine with time limit, let me know when needed.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Bycatch data entry page and report done and in menu system.
At the moment this page uses the same Insect Groups species list as UK PoMS, I will assume that is correct unless I hear otherwise.
The other thing to note is without data, this page is not untested on SPRING. However it is largely the same as UK PoMS which is in live use (apart from configuration) , so I don't expect anything much to be wrong that can't be fixed easily.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Similar notes for Insect Species Data report, assumption in this case that the Master List is correct list to select from.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Is it ok for me to do a full client_helpers update to Master on SPRING test? The dynamic_location form is failing, but I think the problem lies deeper in the client helpers structure (seems to be ok on my machine anyway with latest client helpers Master)
I assume this is ok, but just want to check first.

**Comment by BirenRathod** [comment]
@andrewvanbreda that is not a problem. In fact, you should update regularly while you are working on those sites.

**Comment by andrewvanbreda** [comment]
Not to myself: Problem fixed on Firefox & Chrome, still trouble with Safari but that version is very old, so considered fixed.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
When will you be putting this site live? Let me know when you need me to stop working on it.

I am considering updating iForm before we go live, to iron out a few things

**Comment by BirenRathod** [comment]
@andrewvanbreda I'm waiting from you & @DavidRoy for final go. Can I put it live?

**Comment by DavidRoy** [comment]
@andrewvanbreda let's aim for later today
@BirenRathod how long will it take you?

**Comment by BirenRathod** [comment]
@DavidRoy putting in live env will take 15 to 30 mintues. After that domain and https activation take another one hour time. 

Which domain name is it going to be? is it pollinator-monitoring.net?

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod 
I don't plan to change much to the site before an actually live, as it seems to be reasonably stable at moment.

I might like to do an iForm update first though, that would be easier to do now rather than after live
In particular, the pan-trap form remove species rows icon isn't working, and I don't see how that can be a SPRING specific bug.
Also David might be good to get an answer to #56 if necessary

@BirenRathod 
Let me know if you think I should update iForm or not.

**Comment by BirenRathod** [comment]
@DavidRoy mentioned later on today then @andrewvanbreda can go ahead and change it.

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod 
The iForm update went ok, but didn't seem to make any practical difference.
That problem with species row deletion is still there, but I don't think should hold up go live. After lunch I will do a few checks, then I think we can go live.

**Comment by BirenRathod** [comment]
@andrewvanbreda That is fine let me know one you finish with that.

@DavidRoy are we going to use this domain name-> pollinator-monitoring.net? if yes then we have to register first.

**Comment by DavidRoy** [comment]
@BirenRathod please register the new domain name and make the site live.  Will the domain registration cause a delay?

**Comment by andrewvanbreda** [comment]
@BirenRathod Go ahead Biren. There are always more tests I could do tbh. I will test registration once live anyway.

**Comment by BirenRathod** [comment]
ok thanks. @andrewvanbreda. let you know as soon as I finish that.

**Comment by DavidRoy** [comment]
@andrewvanbreda @BirenRathod just for info, I moved some of the menu navigation around and added some basic content pages

**Comment by BirenRathod** [comment]
@andrewvanbreda & @DavidRoy Initialised the live env now. Unfortunately site will not go live today as there is some work going on domain registration end.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @DavidRoy Here is the live env URL -> https://live-eu-pollinator.pantheonsite.io/

**Comment by andrewvanbreda** [comment]
@BirenRathod
Should I test registration on there now, or should I not touch it until it actually goes live?

**Comment by BirenRathod** [comment]
@andrewvanbreda I have enabled the SMTP module, so yes, you can test the registration.

**Comment by andrewvanbreda** [comment]
Registration passed testing last week apart from a wording problem that was caused by Drupal.
(after you initially set your password, it still asks you to to set it)

@BirenRathod  am I correct in thinking the site is now properly live?
If so, can you not down the final actual proper URL of the final site in this issue, then I will close it.
Cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda Due to domain maintenance work last week, the URL (pollinator-monitoring.net) not registered yet. This will be done by tomorrow noon. After that there will be SSL certificate and IP address point process start. It could be finish by end of tomorrow, if all goes fine. 

So, I wouldn't say properly live yet, so leave for time being open.

**Comment by BirenRathod** [comment]
@andrewvanbreda  & @DavidRoy Just to let you know that this pollinator-monitoring.net domain has registered and live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Great, thanks Biren :)

**Comment by andrewvanbreda** [comment]
Closing this, as system now live. 
Issues to be raised separately.
